name: CI
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v3 # Adds a step to checkout the repository code

    - name: build the app
      run: dotnet build

    - name: build npm
      shell: bash
      run: |
        cd DotnetTemplate.Web
        npm ci 
        echo '##[group]Steves special group'
        echo hello mum
        echo '##[endgroup]'
        npm run build
        help
