name: CI
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed

    defaults:
      run:
        shell: bash
        working-directory: DotnetTemplate.Web

    steps:
    - uses: actions/checkout@v3 # Adds a step to checkout the repository code

    - name: build the app
      run: dotnet build

    - name: npm dependencies and build
      run: |
        npm ci 
        npm run build

    - name: run dotnet tests
      run: dotnet test
    - name: run npm tests
      run: npm test
    - name: lint the typescript
      run: npm run lint
